# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

resources:
  repositories:
    - repository: Analytics # The name used to reference this repository in the checkout step
      type: github
      endpoint: surveyjs
      name: surveyjs/survey-analytics
    - repository: Service # The name used to reference this repository in the checkout step
      type: github
      endpoint: surveyjs
      name: surveyjs/service

trigger:
  batch: true
  branches:
    include:
      - master
  tags:
    exclude:
      - v*.*.*

pool:
  vmImage: "Ubuntu-16.04"

steps:
  - checkout: Service
    persistCredentials: true
    clean: true
  - checkout: Analytics
    persistCredentials: true
    clean: true
    
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      cd $(Build.SourcesDirectory)/survey-analytics
      npm install
    displayName: "npm install"

  - task: DownloadBuildArtifacts@0
    inputs:
      buildType: "specific"
      project: "af2804d2-859a-4705-9ef5-cdf46d1d5d4f"
      pipeline: "7"
      specificBuildWithTriggering: true
      buildVersionToDownload: "latest"
      downloadType: "single"
      artifactName: "SurveyJSLibraryBuild"
      downloadPath: "$(System.ArtifactsDirectory)"

  - task: CopyFiles@2
    inputs:
      SourceFolder: "$(System.ArtifactsDirectory)/SurveyJSLibraryBuild/packages/survey-core"
      Contents: "**"
      TargetFolder: "$(Build.Repository.LocalPath)/node_modules/survey-core"
      OverWrite: true
  
  - script: |
      cd $(Build.SourcesDirectory)/survey-analytics
      npm run build_prod
      npm test
    displayName: "npm build and test"

  - script: |
      cd $(Build.SourcesDirectory)/survey-analytics
      npm run doc_gen
    displayName: 'generate docs'

  - powershell: |
      cd $(Build.SourcesDirectory)/survey-analytics
      echo $(git --version)
      git config --global user.email "kurmanov.work@gmail.com"
      git config --global user.name "dmitrykurmanov"
      npm run doc_update
    displayName: 'update docs'

  - task: CopyFiles@2
    inputs:
      SourceFolder: '$(Build.Repository.LocalPath)/packages'
      targetFolder: $(Build.ArtifactStagingDirectory)/packages/survey-analytics

  - task: PublishBuildArtifacts@1
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'SurveyJSAnalyticsBuild'
      publishLocation: 'Container'